add_newline = true
command_timeout = 2000

format = """
$os\ 
$username\
$hostname\
$directory\
$git_branch$git_status\
$python\
$character
"""

# Drop ugly default prompt characters
[character]
success_symbol = ""
error_symbol = ""

# Shows OS 
[os]
format = '[$symbol](bold white) '   
disabled = false

# OS Symbols
[os.symbols]
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Debian = " "
Fedora = " "
Linux = " "
Macos = " "
Mint = " "
Pop = " "
Ubuntu = " "
Windows = "󰍲 "

# Shows the Username
[username]
disabled = false

# Shows the hostname
[hostname]
disabled = false

# Shows current directory
[directory]
truncation_length = 1
# truncation_symbol = '…/'
home_symbol = '󰋜 ~'
read_only_style = '197'
read_only = '  '
format = '[$path]($style)[$read_only]($read_only_style) '

# Shows current git branch
[git_branch]
symbol = ' '
format = 'via [$symbol$branch]($style)'
truncation_symbol = '…/'
style = 'bold green'

# Shows current git status
[git_status]
conflicted = "=${count}"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?${count}"
stashed = "\\$${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[cmd_duration]
min_time = 500
style = 'fg:gray'
format = '[$duration]($style)'


# --- Tool Section ---

[python]
style = 'teal'
symbol = ' '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true
pyenv_prefix = ''

[vagrant]
disabled = true

[docker_context]
disabled = true

[helm]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[terraform]
disabled = true
