- name: Privileged Setup
  hosts: localhost
  vars:
    remote_regular_user: jershbytes
  become: true
  gather_facts: true

  # Repo Adding
  tasks:
    - name: Install DNF plugins core
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present

    - name: Import Microsoft GPG Key
      ansible.builtin.rpm_key:
        key: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add Visual Studio Code Repo
      ansible.builtin.yum_repository:
        name: vscode
        description: Visual Studio Code
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        gpgcheck: true
        enabled: true

    - name: Add Docker repo
      ansible.builtin.yum_repository:
        name: docker
        description: Docker repo
        baseurl: "https://download.docker.com/linux/fedora/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/stable"
        gpgkey: "https://download.docker.com/linux/fedora/gpg"
        gpgcheck: true
        enabled: true

    - name: Add Hashicorp Repo
      ansible.builtin.yum_repository:
        name: hashicorp
        description: Hashicorp repo
        baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
        gpgkey: https://rpm.releases.hashicorp.com/gpg
        gpgcheck: true
        enabled: true

    - name: Download WezTerm RPM
      ansible.builtin.get_url:
        url: https://github.com/wez/wezterm/releases/download/20240203-110809-5046fc22/wezterm-20240203_110809_5046fc22-1.fedora39.x86_64.rpm
        dest: /tmp/wezterm.rpm
        chm

# Install Apps
    - name: Install packages with DNF
      ansible.builtin.dnf:
        name:
          - code
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - terraform
          - flatpak
          - gcc-c++
          - make
          - curl
        state: present

    - name: Install WezTerm RPM
      ansible.builtin.dnf:
        name: /tmp/wezterm.rpm
        state: present
        disable_gpg_check: true

    - name: Clean up downloaded RPM
      ansible.builtin.file:
        path: /tmp/wezterm.rpm
        state: absent

    - name: Add Docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ remote_regular_user }}"
        groups: docker
        append: true

    - name: Add Flathub repository
      ansible.builtin.shell: |
        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      args:
        creates: /var/lib/flatpak/repo/flathub

- name: Non-Privileged Setup
  hosts: localhost
  vars:
    remote_regular_user: jershbytes
  become: false
  connection: localhost

  tasks:
    - name: Install Brew packages
      community.general.homebrew:
        name:
          - oh-my-posh
          - yazi
          - neovim
          - neovide
          - ripgrep
          - fd
          - zig
          - lazygit
          - fzf
          - zoxide
          - hugo
          - lolcat
          - fortune
          - cowsay
        state: present

    - name: Install Flatpak packages
      community.general.flatpak:
        name:
          - tv.plex.PlexDesktop
          - dev.aunetx.deezer
          - com.bitwarden.desktop
          - dev.vencord.Vesktop
          - org.kde.haruna
        state: present
