### Add Repositories ###
- name: Add Repositories
  hosts: localhost
  vars:
    remote_regular_user: "{{ ansible_user }}"
  become: true
  gather_facts: true
  tasks:
    
    - name: Install DNF plugins core
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present

    - name: Add Hashicorp Repo
      ansible.builtin.yum_repository:
        name: hashicorp
        description: Hashicorp repo
        baseurl: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
        gpgkey: https://rpm.releases.hashicorp.com/gpg
        gpgcheck: true
        enabled: true

- name: Install DNF Applications
  hosts: localhost
  vars:
    remote_regular_user: "{{ ansible_user }}"
  become: true
  gather_facts: true
  tasks:
    
    - name: Install packages with DNF
      ansible.builtin.dnf:
        name:
          - gcc-c++
          - make
          - curl
          - fping
          - zsh
          - terraform
        state: present

- name: Hombrew Application Install
  hosts: localhost
  vars:
    remote_regular_user: "{{ ansible_user }}"
  become: false
  connection: localhost

  tasks:
    - name: Install Brew packages
      community.general.homebrew:
        name:
          - neovim
          - neovide
          - ripgrep
          - fd
          - zig
          - lazygit
          - fzf
          - zoxide
          - hugo
          - lolcat
          - fortune
          - cowsay
          - starship
        state: present
