### Add Repositories ###
- name: Add Repositories
  hosts: localhost
  vars:
    remote_regular_user: jershbytes
  become: true
  gather_facts: true
  tasks:
    - name: Install APT transport
      apt:
        name: apt-transport-https
        state: present

    - name: Install Terraform using HashiCorp repository
      shell: |
        wget -O - https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
        apt update && apt install -y terraform
    
    - name: Add Docker
      shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh

### Install APT Applications ###
- name: Install APT Applications
  hosts: localhost
  become: true
  gather_facts: true
  vars:
    remote_regular_user: jershbytes  # Set the remote user here
  tasks:
    - name: Install packages with APT
      apt:
        name:
          - g++
          - make
          - curl
          - fping
          - zsh
        state: present

    - name: Add user to the Docker group
      user:
        name: "{{ remote_regular_user }}"
        groups: docker
        append: yes

    - name: Install Oh My Zsh
      shell: |
        sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" || true

### Homebrew Application Install ###
- name: Homebrew Application Install
  hosts: localhost
  vars:
    remote_regular_user: "{{ remote_regular_user }}"
  become: false
  connection: localhost
  tasks:
    - name: Install Brew packages
      community.general.homebrew:
        name:
          - neovim
          - neovide
          - ripgrep
          - fd
          - zig
          - lazygit
          - fzf
          - zoxide
          - hugo
          - lolcat
          - fortune
          - cowsay
          - starship
        state: present
