### Add Repositories ###
- name: Add Repositories
  hosts: localhost
  become: true
  gather_facts: true
  tasks:
    - name: Install APT transport
      apt:
        name: apt-transport-https
        state: present

### Install APT Applications ###
- name: Install APT Applications
  hosts: localhost
  become: true
  gather_facts: true
  vars:
    remote_regular_user: jershbytes  # Set the remote user here
  tasks:
    - name: Install packages with APT
      apt:
        name:
          - g++
          - make
          - curl
          - fping
        state: present

### Homebrew Application Install ###
- name: Homebrew Application Install
  hosts: localhost
  vars:
    remote_regular_user: "{{ remote_regular_user }}"
  become: false
  connection: localhost
  tasks:
    - name: Install Brew packages
      community.general.homebrew:
        name:
          - neovim
          - ripgrep
          - fd
          - zig
          - lazygit
          - fzf
          - zoxide
          - hugo
          - lolcat
          - fortune
          - starship
          - docker
          - terraform
          - zsh
        state: present
