---
- name: Arch Linux System Setup
  hosts: localhost
  become: true
  tasks:
    - name: Create the `aur_builder` user
      ansible.builtin.user:
        name: aur_builder
        create_home: true
        group: wheel

    - name: Allow the `aur_builder` user to run `sudo pacman` without a password
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: true
        mode: "0644"
        validate: 'visudo -cf %s'

    - name: Install Ansible Galaxy collections
      ansible.builtin.command:
        cmd: >
          ansible-galaxy collection install
          ansible.posix
          community.general
        creates: ~/.ansible/collections/ansible_collections

    - name: Update package list
      community.general.pacman:
        update_cache: true
        upgrade: true

- name: Install Pacman packages
  hosts: localhost
  become: true
  vars:
    pacman_packages:
      - wezterm
      - tree
      - gnupg
      - ansible-lint
      - chezmoi
      - neovim
      - ripgrep
      - fzf
      - fd
      - zig
      - lazygit
      - zoxide
      - hugo
      - starship
      - lolcat
      - bitwarden
  tasks:
    - name: Install Pacman packages
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop: "{{ pacman_packages }}"


- name: Install AUR packages
  hosts: localhost
  become: true
  become_user: "aur_builder"
  vars:
    aur_packages:
      - plex-desktop
      - legcord
      - proton-mail
      - visual-studio-code-bin
  tasks:
    - name: Install AUR packages
      community.general.pacman:
        name: "{{ item }}"
        state: present
        executable: yay
      loop: "{{ aur_packages }}"
