---
- name: Configure Debian environment
  hosts: localhost
  become: true
  vars:
    remote_regular_user: jershbytes
  tasks:
    - name: Create update script file
      ansible.builtin.copy:
        dest: /usr/local/bin/update
        content: |
          sudo apt update
          sudo apt upgrade
        mode: '0755'

    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - software-properties-common
          - sshpass
          - python3-full
          - python3-requests
          - python3-pip
          - whois
          - traceroute
          - mc
          - wireshark
          - terminator
          - bind9-dnsutils
          - tree
          - gnupg2
          - ansible-lint
          - zsh 
        state: present
        update_cache: true

    - name: Install Ansible Galaxy collections
      ansible.builtin.command:
        cmd: >
          ansible-galaxy collection install
          ansible.posix
          community.general
          community.windows
          ansible.windows
        creates: ~/.ansible/collections/ansible_collections

- name: Homebrew Application Install
  hosts: localhost
  vars:
    remote_regular_user: "{{ remote_regular_user }}"
  become: false
  connection: localhost
  tasks:
    - name: Install Brew packages
      community.general.homebrew:
        name:
          - chezmoi
          - neovim
          - ripgrep
          - fd
          - zig
          - lazygit
          - fzf
          - zoxide
          - hugo
          - lolcat
          - fortune
          - starship
        state: present
