
### Add Repositories ###
- name: Add Repositories
  hosts: localhost
  vars:
    remote_regular_user: "{{ ansible_user }}"
  become: true
  gather_facts: true
  tasks:
    
    - name: Install DNF plugins core
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present
    
    - name: Install yum-utils packages
      ansible.builtin.dnf:
        name: yum-utils
        state: present

    - name: Add Docker repo
      ansible.builtin.yum_repository:
        name: docker-ce
        description: "Docker CE Repository"
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo
        enabled: yes
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
    
    - name: Add Hashicorp Repo
      ansible.builtin.yum_repository:
        name: hashicorp
        description: "HashiCorp Stable - RHEL"
        baseurl: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
        gpgkey: https://rpm.releases.hashicorp.com/gpg
        gpgcheck: true
        enabled: true

- name: Install DNF Applications
  hosts: localhost
  vars:
    remote_regular_user: "{{ ansible_user }}"
  become: true
  gather_facts: true
  tasks:
    
    - name: Install packages with DNF
      ansible.builtin.dnf:
        name:
          - terraform
          - gcc-c++
          - make
          - curl
          - fping
          - zsh
        state: present

    - name: Add Docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ remote_regular_user }}"
        groups: docker
        append: true

- name: Hombrew Application Install
  hosts: localhost
  vars:
    remote_regular_user: "{{ ansible_user }}"
  become: false
  connection: localhost

  tasks:
    - name: Install Brew packages
      community.general.homebrew:
        name:
          - neovim
          - neovide
          - ripgrep
          - fd
          - zig
          - lazygit
          - fzf
          - zoxide
          - hugo
          - lolcat
          - fortune
          - cowsay
          - starship
          - chezmoi
        state: present
